main: xyz.ufactions.gsp.GreenStress
name: GreenStress
author: ProFewGames
version: 1.8.8
commands:
  stress:
    description: Master command
    aliases: [greenstress, gs]
  spawn:
    description: Return to spawn
  fly:
    description: Soar through the air like a bird
  reset:
    description: Reset the stress world
  weather:
    description: Manipulate worlds
    aliases: [toggledownfall, norain, time, day, night, sunset]
  world:
    description: Teleport or view worlds
  lag:
    description: View the server info
    aliases: [tps, gc, lag, mem, memory, uptime]
permissions:
  stress.command.admin:
    description: Administrator permissions
  weather.command:
    description: Weather GUI Command